#!/usr/bin/env bash
# Publish titan.zybuu.com through a Cloudflare Tunnel.
#
# Why a tunnel rather than the port-forward this repo originally assumed:
# Airtel puts this connection behind carrier-grade NAT. The router's WAN
# address is 100.108.60.116, inside 100.64.0.0/10 — the reserved CGNAT range —
# while the internet sees 171.76.80.224, an address Airtel shares between many
# customers. Forwarding a port on the router moves traffic inward from an
# address nothing on the internet can reach, so no inbound connection, and
# therefore no HTTP-01 certificate, is possible from here at all.
#
# A tunnel inverts the direction: cloudflared dials OUT to Cloudflare and holds
# the connection open, and requests arrive back down it. Outbound is the one
# thing CGNAT does not block.
#
# The security trade-off, stated plainly: traffic transits Cloudflare, who
# terminate TLS and can see it. In exchange the home IP is never published, no
# port is opened on the router, and their edge absorbs scanning and DDoS before
# any of it reaches this machine. For an agent that runs shell commands, that is
# a better bargain than exposing the address directly — but it IS a third party
# in the path, which an air-gapped deployment would not accept.
set -euo pipefail

DOMAIN="${TITAN_DOMAIN:-titan.zybuu.com}"
TUNNEL="${TITAN_TUNNEL:-titan}"
LOCAL="${TITAN_LOCAL:-http://127.0.0.1:8080}"
CFG_DIR="$HOME/.cloudflared"

step() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }

command -v cloudflared >/dev/null 2>&1 || {
  echo "error: cloudflared not installed (brew install cloudflared)" >&2; exit 1; }

# ---------------------------------------------------------------- 1. account
# The browser step cannot be automated: it authorises this machine against a
# Cloudflare account and writes a certificate only that login can produce.
if [ ! -f "$CFG_DIR/cert.pem" ]; then
  step "Authorise this machine with Cloudflare"
  echo "A browser will open. Sign in, then pick the zone for zybuu.com."
  echo "If zybuu.com is not listed, add it to Cloudflare first — free plan is"
  echo "enough — and point GoDaddy's nameservers at Cloudflare when asked."
  cloudflared tunnel login
fi

# ------------------------------------------------------------------ 2. tunnel
if ! cloudflared tunnel list 2>/dev/null | awk '{print $2}' | grep -qx "$TUNNEL"; then
  step "Creating tunnel '$TUNNEL'"
  cloudflared tunnel create "$TUNNEL"
else
  echo "tunnel '$TUNNEL' already exists"
fi

TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL" '$2==n {print $1}' | head -1)"
[ -n "$TUNNEL_ID" ] || { echo "error: could not resolve tunnel id" >&2; exit 1; }

# ------------------------------------------------------------------ 3. config
step "Writing $CFG_DIR/config.yml"
cat > "$CFG_DIR/config.yml" <<YAML
# Generated by deploy/tunnel.sh
tunnel: $TUNNEL_ID
credentials-file: $CFG_DIR/$TUNNEL_ID.json

ingress:
  - hostname: $DOMAIN
    service: $LOCAL
    originRequest:
      # Server-sent events are the console's transport. Without this the
      # transcript arrives in one lump when the run finishes instead of
      # streaming as the agent works.
      disableChunkedEncoding: false
      # An agent run is long; the default 30s idle timeout would cut the
      # event stream mid-session.
      connectTimeout: 30s
      tcpKeepAlive: 30s
  # Anything not matching the hostname above is refused rather than proxied.
  - service: http_status:404
YAML

# ---------------------------------------------------------------------- 4. DNS
# This replaces the A record with a CNAME to the tunnel. The A record pointed at
# a CGNAT-shared address that never answered, so nothing is lost.
step "Pointing $DOMAIN at the tunnel"
cloudflared tunnel route dns "$TUNNEL" "$DOMAIN" 2>&1 | tail -2 || \
  echo "note: route may already exist — continuing"

step "Ready"
cat <<TEXT

Run the tunnel:

    cloudflared tunnel run $TUNNEL

Or install it as a service that survives a reboot:

    sudo cloudflared service install
    sudo launchctl start com.cloudflare.cloudflared

Then check from OUTSIDE this network (phone on mobile data):

    https://$DOMAIN

TEXT
